version: "3.9"
services:
    minio:
        container_name: ${APP_NAME}-minio
        image: minio/minio
        ports:
            - '${MINIO_API_PORT}:9000'
            - '${MINIO_CLI_PORT}:9011'
        volumes:
            - ./${BASE_DIR}/minio/data/:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server --console-address ":${MINIO_CLI_PORT}" /data/
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAME}-minio.loadbalancer.server.port=9000"
            - "traefik.http.routers.${APP_NAME}-minio.rule=Host(`${APP_NAME}-minio-api`)"
            - "traefik.http.routers.${APP_NAME}-minio.service=${APP_NAME}-minio"
            - "traefik.http.routers.${APP_NAME}-minio.entrypoints=http"

            - "traefik.http.services.${APP_NAME}-minio-console.loadbalancer.server.port=9011"
            - "traefik.http.routers.${APP_NAME}-minio-console.rule=Host(`${APP_NAME}-minio`)"
            - "traefik.http.routers.${APP_NAME}-minio-console.service=${APP_NAME}-minio-console"
            - "traefik.http.routers.${APP_NAME}-minio-console.entrypoints=http"
            - "traefik.docker.network=gateway"
        networks:
            - gateway
    minio-service:
        container_name: ${APP_NAME}-minio-service
        image: minio/mc
        restart: on-failure
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc alias set vyMinio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
            /usr/bin/mc mb vyMinio/${MINIO_BUCKET_STRAPI};
            /usr/bin/mc anonymous set public vyMinio/${MINIO_BUCKET_STRAPI};
            "
        networks:
            - gateway