api:
    dashboard: true
entryPoints:
    http:
        address: ":80"
    https:
        address: ":443"
    strapi:
        address: ":1337"
    minio:
        address: ":9000"
providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
    file:
        directory: /custom
        watch: true