nelmio_api_doc:
    documentation:
        info:
            title: User
            description: Module
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
